name: events_app_trueattempt
description: "A new Flutter project."

publish_to: "none"

version: 0.1.5+6

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.3.6

  # State Management
  flutter_riverpod: ^2.5.1
  
  # UI & Utilities
  google_fonts: ^6.2.1
  intl: ^0.19.0
  card_swiper: ^3.0.1
  flutter_svg: ^2.0.10+1
  table_calendar: ^3.0.9 # Use latest stable version

  # For Push Notifications
  firebase_messaging: ^15.2.10
  
  # For QR Code Generation (for speakers)
  qr_flutter: ^4.1.0
  
  # For QR Code Scanning (for attendees)
  mobile_scanner: 3.5.7
  
  # For opening Live Stream links
  url_launcher: ^6.2.1
  
  # For YouTube video player
  youtube_player_flutter: ^9.0.3

  #for remote configuration of app
  firebase_remote_config: ^5.5.0

  #animations
  flutter_staggered_animations: ^1.1.1

  #cloud functions
  cloud_functions: ^5.6.2

  # For grouping data collections
  collection: ^1.17.2

  # For QR download functionality
  pdf: ^3.11.1
  
  # For relative time formatting
  timeago: ^3.7.0
  printing: ^5.13.4
  share_plus: ^10.1.3
  path_provider: ^2.1.5

  # For charts and analytics (test)
  fl_chart: ^0.69.0

  # For persistent storage
  shared_preferences: ^2.2.2

  # For image selection and cropping
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  
  # For cached network images
  cached_network_image: ^3.4.1
  
  # For app version info
  package_info_plus: ^8.0.0
  font_awesome_flutter: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#001F3F" # Navy blue background
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/images/
    - assets/images/tmp/
    - assets/icons/
