// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABCDknpSAZBFFsGbh_AE5rNaipFzu6K5A',
    appId: '1:266662172572:web:4cef3bf5b004c3a88fda59',
    messagingSenderId: '266662172572',
    projectId: 'events-app3',
    authDomain: 'events-app3.firebaseapp.com',
    storageBucket: 'events-app3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChKRAqK12x6-d_kEYvLHmTZYiVpaKIwRY',
    appId: '1:266662172572:android:a126e7dd9d828b258fda59',
    messagingSenderId: '266662172572',
    projectId: 'events-app3',
    storageBucket: 'events-app3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdghmuQ6AH8sxCNb8-_LfTuxp2EkrBRAo',
    appId: '1:266662172572:ios:4256291f6b22590f8fda59',
    messagingSenderId: '266662172572',
    projectId: 'events-app3',
    storageBucket: 'events-app3.firebasestorage.app',
    iosBundleId: 'org.namafoundation.eventapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdghmuQ6AH8sxCNb8-_LfTuxp2EkrBRAo',
    appId: '1:266662172572:ios:2791da9e9770d39b8fda59',
    messagingSenderId: '266662172572',
    projectId: 'events-app3',
    storageBucket: 'events-app3.firebasestorage.app',
    iosBundleId: 'com.example.eventsAppTrueattempt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJvfq0CulDcbT_BpV-W3CxdeI0QoV6YfU',
    appId: '1:266662172572:web:8c79ad95eae12a268fda59',
    messagingSenderId: '266662172572',
    projectId: 'events-app3',
    authDomain: 'events-app3.firebaseapp.com',
    storageBucket: 'events-app3.firebasestorage.app',
  );
}
