import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter/foundation.dart';
import 'app.dart';
import 'firebase_options.dart'; // This file is generated by flutterfire
import 'utils/seed_data.dart';
import 'utils/test_live_session.dart';
import 'package:events_app_trueattempt/core/providers.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Seeding configuration
  // Set this to true if you want to seed data on app startup
  // WARNING: Only set to true on first run or when you need to populate test data
  const bool shouldSeedData = false; // Change to true to seed data
  const bool shouldAddTestLiveSession = false; // Add single test live session
  const bool shouldAddMultipleTestSessions = false; // Add multiple sessions to test priority system

  // Seed data if enabled (you can ignore the "dead code" warning - it's intentional for safety)
  // ignore: dead_code
  if (shouldSeedData) {
    try {
      await SeedData.seedAllData();
      debugPrint('Data seeding completed successfully!');
    } catch (e) {
      debugPrint('Error seeding data: $e');
    }
  }

  // Add test live session for YouTube player testing
  // ignore: dead_code
  if (shouldAddTestLiveSession) {
    try {
      await TestLiveSession.addTestLiveSession();
      debugPrint('Single test live session added successfully!');
    } catch (e) {
      debugPrint('Error adding test live session: $e');
    }
  }

  // Add multiple test sessions to demonstrate priority system
  // ignore: dead_code
  if (shouldAddMultipleTestSessions) {
    try {
      await TestLiveSession.addMultipleTestSessions();
      debugPrint('Multiple test sessions added successfully!');
    } catch (e) {
      debugPrint('Error adding multiple test sessions: $e');
    }
  }
  // Initialize Remote Config
  final container = ProviderContainer();
  await container.read(remoteConfigServiceProvider).initialize();

  runApp(
    UncontrolledProviderScope(
      container: container,
      child: const MyApp(),
    ),
  );
}