import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter/foundation.dart';
import 'app.dart';
import 'firebase_options.dart'; // This file is generated by flutterfire
import 'utils/seed_data.dart';

void main() async {
  // Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Seeding configuration
  // Set this to true if you want to seed data on app startup
  // WARNING: Only set to true on first run or when you need to populate test data
  const bool shouldSeedData = false; // Change to true to seed data

  // Seed data if enabled (you can ignore the "dead code" warning - it's intentional for safety)
  // ignore: dead_code
  if (shouldSeedData) {
    try {
      await SeedData.seedAllData();
      debugPrint('Data seeding completed successfully!');
    } catch (e) {
      debugPrint('Error seeding data: $e');
    }
  }
  
  runApp(
    const ProviderScope(
      child: MyApp(),
    ),
  );
}